# Stage 1: Build React app
FROM node:18-alpine AS build

WORKDIR /frontend                # Use /app instead of /my-app for simplicity
COPY package*.json ./        # Copy package.json & package-lock.json
RUN npm ci                   # Clean install for CI/CD consistency
COPY . .                     # Copy all source files

ARG REACT_APP_URL
ENV REACT_APP_URL=$REACT_APP_URL

RUN npm run build             # Build production-ready React app

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html  # Copy built app to Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
