
FROM node:18-alpine AS test
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install         
COPY . .
ARG http://13.53.201.45:9000/
ENV REACT_APP_URL=http://13.53.201.45:9000/
RUN npm run build


FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
