services:
  backend:
    build: ./fashionbackend
    container_name: fashion-backend
    ports:
      - "9000:9000"
    networks:
      - net-backend

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_URL: http://13.233.183.191:9000
    container_name: fashion-frontend
    ports:
      - "80:80"  
    networks:
      - net-backend

networks:
  net-backend:
    driver: bridge
