name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Debug repo structure
      - name: List project files
        run: ls -R

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      # Step 5: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: frontend

      # Step 6: Build project
      - name: Build project
        run: npm run build
        working-directory: frontend
